 # Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load Dataset

In [2]:
Amazon_Sale = pd.read_csv("E:/SQL Project Content/archive (3)/Amazon Sale Report.csv")

C:\Users\ankit\AppData\Local\Temp\ipykernel_9264\2012349315.py:1: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  Amazon_Sale = pd.read_csv("E:/SQL Project Content/archive (3)/Amazon Sale Report.csv")

# Data Understanding

In [3]:
Amazon_Sale.shape

(128975, 24)

In [4]:
Amazon_Sale.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [5]:
Amazon_Sale.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='str')

In [6]:
Amazon_Sale.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(1), str(18)
memory usage: 22.8+ MB

# Data Quality Check

In [7]:
Amazon_Sale.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [8]:
Amazon_Sale.duplicated().sum()

np.int64(0)

In [9]:
Amazon_Sale.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

# Handling Missing Values

In [10]:
Amazon_Sale["index"].equals(pd.Series(range(len(Amazon_Sale)),index=Amazon_Sale.index))

True

In [11]:
Amazon_Sale.drop("index", axis=1, inplace=True)

In [12]:
Amazon_Sale.shape

(128975, 23)

In [13]:
Amazon_Sale["Unnamed: 22"].value_counts(dropna=False)

Unnamed: 22
False    79925
NaN      49050
Name: count, dtype: int64

In [14]:
Amazon_Sale["Unnamed: 22"].head(20)

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
Name: Unnamed: 22, dtype: object

In [15]:
Amazon_Sale.drop("Unnamed: 22" , axis = 1,inplace = True)

In [16]:
Amazon_Sale.shape

(128975, 22)

# Data Type Conversion

In [23]:
Amazon_Sale["Date"] = pd.to_datetime(
    Amazon_Sale["Date"],
    format = "%m-%d-%y")

In [24]:
Amazon_Sale["Date"].dtype

dtype('<M8[us]')

In [25]:
Amazon_Sale["Date"].isnull().sum()

np.int64(0)

In [36]:
missing_percentage = Amazon_Sale.isnull().sum() / len(Amazon_Sale) *100

In [37]:
missing_percentage

Order ID               0.000000
Date                   0.000000
Status                 0.000000
Fulfilment             0.000000
Sales Channel          0.000000
ship-service-level     0.000000
Style                  0.000000
SKU                    0.000000
Category               0.000000
Size                   0.000000
ASIN                   0.000000
Courier Status         5.328164
Qty                    0.000000
currency               6.043807
Amount                 6.043807
ship-city              0.025586
ship-state             0.025586
ship-postal-code       0.025586
ship-country           0.025586
promotion-ids         38.110487
B2B                    0.000000
fulfilled-by          69.546811
dtype: float64

In [41]:
missing_percentage.sort_values(ascending=False)

fulfilled-by          69.546811
promotion-ids         38.110487
currency               6.043807
Amount                 6.043807
Courier Status         5.328164
ship-country           0.025586
ship-postal-code       0.025586
ship-state             0.025586
ship-city              0.025586
ship-service-level     0.000000
Fulfilment             0.000000
B2B                    0.000000
Status                 0.000000
Sales Channel          0.000000
Style                  0.000000
Qty                    0.000000
Date                   0.000000
ASIN                   0.000000
Size                   0.000000
Category               0.000000
SKU                    0.000000
Order ID               0.000000
dtype: float64

In [42]:
Amazon_Sale[Amazon_Sale["Amount"].isnull()].head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
8,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,3XL,...,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
29,404-5933402-8801952,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,3XL,...,0,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,NaN,False,Easy Ship
65,171-4137548-0481151,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,XXL,...,0,NaN,NaN,Dahod,Gujarat,389151.0,IN,NaN,False,NaN
84,403-9950518-0349133,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,M,...,0,NaN,NaN,HYDERABAD,TELANGANA,500072.0,IN,NaN,False,NaN
95,405-9112089-3379536,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,L,...,0,NaN,NaN,PUNE,MAHARASHTRA,411046.0,IN,NaN,False,NaN

In [43]:
Amazon_Sale[Amazon_Sale["Courier Status"].isnull()].head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship
23,404-6019946-2909948,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET291,SET291-KR-PP-M,Set,M,...,0,INR,570.48,pune,MAHARASHTRA,411044.0,IN,NaN,False,Easy Ship
29,404-5933402-8801952,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,3XL,...,0,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,NaN,False,Easy Ship
83,404-6522553-9345930,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET377,SET377-KR-NP-M,Set,M,...,0,INR,1105.36,DEHRADUN,UTTARAKHAND,248001.0,IN,NaN,False,Easy Ship

In [44]:
Amazon_Sale[Amazon_Sale["fulfilled-by"].isnull()].head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,1,INR,329.0,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,1,INR,574.0,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN
5,404-1490984-4578765,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,XL,...,1,INR,824.0,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
6,408-5748499-6859555,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,L,...,1,INR,653.0,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
8,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,3XL,...,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN

In [45]:
Amazon_Sale[Amazon_Sale["Amount"].isnull()].head(10)

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
8,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,3XL,...,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
29,404-5933402-8801952,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,3XL,...,0,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,NaN,False,Easy Ship
65,171-4137548-0481151,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,XXL,...,0,NaN,NaN,Dahod,Gujarat,389151.0,IN,NaN,False,NaN
84,403-9950518-0349133,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,M,...,0,NaN,NaN,HYDERABAD,TELANGANA,500072.0,IN,NaN,False,NaN
95,405-9112089-3379536,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,L,...,0,NaN,NaN,PUNE,MAHARASHTRA,411046.0,IN,NaN,False,NaN
101,402-7841951-1872363,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET347,SET347-KR-NP-S,Set,S,...,0,NaN,NaN,NEW DELHI,DELHI,110036.0,IN,NaN,False,NaN
132,171-0293372-4913973,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET269,SET269-KR-NP-XXXL,Set,3XL,...,0,NaN,NaN,KOLAR,KARNATAKA,563101.0,IN,NaN,False,NaN
139,403-6442534-2769112,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,J0300,J0300-TP-XXXL,Top,3XL,...,0,NaN,NaN,AZAMGARH,UTTAR PRADESH,276302.0,IN,NaN,False,NaN
155,402-8078642-8565124,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,JNE3887,JNE3887-KR-XL,kurta,XL,...,0,NaN,NaN,Puri-2,ODISHA,752002.0,IN,NaN,False,NaN
165,406-0218328-1773963,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,PJNE2100,PJNE2100-KR-N-6XL,kurta,6XL,...,0,NaN,NaN,WALAJAPET,TAMIL NADU,632513.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN

# Data Standardization

In [46]:
Amazon_Sale[Amazon_Sale["Amount"].isnull()][
    ["Status", "Qty", "currency", "Amount"]
].value_counts(dropna=False)

Status                        Qty  currency  Amount
Cancelled                     0    NaN       NaN       7565
Shipped                       1    NaN       NaN        106
                              0    NaN       NaN         93
Shipped - Delivered to Buyer  0    NaN       NaN          8
Shipping                      1    NaN       NaN          8
Shipped                       2    NaN       NaN          4
Shipped - Returned to Seller  0    NaN       NaN          3
Pending                       0    NaN       NaN          2
Shipped                       15   NaN       NaN          1
                              9    NaN       NaN          1
                              13   NaN       NaN          1
Cancelled                     1    NaN       NaN          1
Shipped                       4    NaN       NaN          1
                              3    NaN       NaN          1
Name: count, dtype: int64

In [48]:
Amazon_Sale["currency"].isnull().value_counts() == Amazon_Sale["Amount"].isnull().value_counts()

currency
False    True
True     True
Name: count, dtype: bool

In [50]:
Amazon_Sale["currency"].isnull().sum()

np.int64(7795)

In [51]:
Amazon_Sale["Amount"].isnull().sum()

np.int64(7795)

In [52]:
Amazon_Sale[Amazon_Sale["Amount"].isnull()]["Status"].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [54]:
missing_amount_percentage= Amazon_Sale["Amount"].isnull().sum() / len(Amazon_Sale) * 100

In [55]:
missing_amount_percentage

np.float64(6.043806939329328)

In [56]:
Amazon_Sale[Amazon_Sale["Amount"].isnull()]["Fulfilment"].value_counts()

Fulfilment
Amazon      6059
Merchant    1736
Name: count, dtype: int64

In [57]:
Amazon_Sale[Amazon_Sale["Amount"].isnull()]["Courier Status"].value_counts(dropna=False)

Courier Status
Cancelled    5935
NaN          1736
Unshipped     124
Name: count, dtype: int64

In [58]:
Amazon_Sale["fulfilled-by"].value_counts(dropna=False)

fulfilled-by
NaN          89698
Easy Ship    39277
Name: count, dtype: int64

In [59]:
Amazon_Sale.groupby(["Fulfilment", "fulfilled-by"], dropna=False).size()

Fulfilment  fulfilled-by
Amazon      NaN             89698
Merchant    Easy Ship       39277
dtype: int64

In [60]:
Amazon_Sale.drop(columns=["fulfilled-by"], inplace=True)

In [62]:
Amazon_Sale.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B'],
      dtype='str')

In [63]:
Amazon_Sale["promotion-ids"].value_counts().head(10)

promotion-ids
IN Core Free Shipping 2015/04/08 23-48-5-108                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              46100
Duplicated A12RHGVGRWOT3S 1560498941486                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     489
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-XX7G3ZRJJJ5LG,Amazon PLCC Free-Financing Universal Merchant AAT-LEHCKNDBJG64E,Amazon PLCC Free-Financing Universal Merchant AAT-DJVHCEV7D7RQY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      458
Duplicated AYTJSBA8ZOP16 1567159860988                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      433
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      316
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      305
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4      230
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-FYWJCQHU2XQ2U,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-URPEBMPS7TSPE,Amazon PLCC Free-Financing Universal Merchant AAT-5ZEB2OGNZ32MC,Amazon PLCC Free-Financing Universal Merchant AAT-YZ2VQO2YM6YYM,Amazon PLCC Free-Financing Universal Merchant AAT-4EOBCMLXMLDGY,Amazon PLCC Free-Financing Universal Merchant AAT-UB6CYNTOQMM7C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                      206
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-YFJA6XMAMWZSK,Amazon PLCC Free-Financing Universal Merchant AAT-K66BSCE2J2V5E,Amazon PLCC Free-Financing Universal Merchant AAT-275LMAQ3T5REI,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                                                                                      201
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-FYWJCQHU2XQ2U,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-URPEBMPS7TSPE,Amazon PLCC Free-Financing Universal Merchant AAT-YZ2VQO2YM6YYM,Amazon PLCC Free-Financing Universal Merchant AAT-4EOBCMLXMLDGY,Amazon PLCC Free-Financing Universal Merchant AAT-UB6CYNTOQMM7C,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4                                                                                                                                                                                                                                                                                                                                      198
Name: count, dtype: int64

# Duplicate Data Removal

In [67]:
Amazon_Sale["promotion-ids"] = Amazon_Sale["promotion-ids"].fillna("No Promotion")

In [68]:
Amazon_Sale["promotion-ids"].value_counts().head()

promotion-ids
No Promotion                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              49153
IN Core Free Shipping 2015/04/08 23-48-5-108                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              46100
Duplicated A12RHGVGRWOT3S 1560498941486                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     489
Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-G5ZRX4BZOIODU,Amazon PLCC Free-Financing Universal Merchant AAT-PZHUW6DZX4BPS,Amazon PLCC Free-Financing Universal Merchant AAT-XX7G3ZRJJJ5LG,Amazon PLCC Free-Financing Universal Merchant AAT-LEHCKNDBJG64E,Amazon PLCC Free-Financing Universal Merchant AAT-DJVHCEV7D7RQY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4      458
Duplicated AYTJSBA8ZOP16 1567159860988                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      433
Name: count, dtype: int64

In [69]:
Amazon_Sale[
    Amazon_Sale["ship-city"].isnull()
][
    ["Order ID", "ship-city", "ship-state", "ship-postal-code", "ship-country"]
]

,Order ID,ship-city,ship-state,ship-postal-code,ship-country
1871,404-0566904-4825137,NaN,NaN,NaN,NaN
1872,404-0566904-4825137,NaN,NaN,NaN,NaN
8752,406-4003386-8768363,NaN,NaN,NaN,NaN
11215,402-0107720-7057168,NaN,NaN,NaN,NaN
13252,407-4532637-8415521,NaN,NaN,NaN,NaN
15688,404-9229894-8608305,NaN,NaN,NaN,NaN
16787,402-4919636-4333150,NaN,NaN,NaN,NaN
18351,405-4927647-8064368,NaN,NaN,NaN,NaN
22930,402-8628677-0457954,NaN,NaN,NaN,NaN
24986,406-4079063-8291520,NaN,NaN,NaN,NaN
30379,404-7506843-7913132,NaN,NaN,NaN,NaN
37963,407-3064376-9158743,NaN,NaN,NaN,NaN
37964,407-3064376-9158743,NaN,NaN,NaN,NaN
60986,171-3257610-9237139,NaN,NaN,NaN,NaN
63040,402-1049475-3611523,NaN,NaN,NaN,NaN
73675,405-1356730-8598722,NaN,NaN,NaN,NaN
73746,407-4664354-2179554,NaN,NaN,NaN,NaN
73771,406-7680604-5439529,NaN,NaN,NaN,NaN
73772,406-7680604-5439529,NaN,NaN,NaN,NaN
73911,405-3420451-5230744,NaN,NaN,NaN,NaN
80011,171-4552355-0255565,NaN,NaN,NaN,NaN
80092,403-2857451-7335536,NaN,NaN,NaN,NaN
80455,171-4691098-8489159,NaN,NaN,NaN,NaN
84008,405-8605864-8021901,NaN,NaN,NaN,NaN
84757,402-8651786-0683548,NaN,NaN,NaN,NaN
104201,403-3190636-2013146,NaN,NaN,NaN,NaN
106498,402-8673941-7883531,NaN,NaN,NaN,NaN
124215,405-0340492-2359532,NaN,NaN,NaN,NaN
124357,405-5884153-9925116,NaN,NaN,NaN,NaN
124358,405-5884153-9925116,NaN,NaN,NaN,NaN
124359,405-5884153-9925116,NaN,NaN,NaN,NaN
125385,403-5172380-9787567,NaN,NaN,NaN,NaN
126620,403-4249038-6582716,NaN,NaN,NaN,NaN

In [70]:
Amazon_Sale[
    Amazon_Sale["ship-city"].isnull()
]["Status"].value_counts()

Status
Shipped                         16
Cancelled                        7
Shipped - Delivered to Buyer     7
Shipped - Returned to Seller     3
Name: count, dtype: int64

In [71]:
Amazon_Sale["ship-city"] = Amazon_Sale["ship-city"].fillna("Unknown")
Amazon_Sale["ship-state"] = Amazon_Sale["ship-state"].fillna("Unknown")
Amazon_Sale["ship-country"] = Amazon_Sale["ship-country"].fillna("Unknown")

In [72]:
Amazon_Sale[["ship-city", "ship-state", "ship-country"]].isnull().sum()

ship-city       0
ship-state      0
ship-country    0
dtype: int64

In [73]:
Amazon_Sale["ship-postal-code"].dtype

dtype('float64')

In [74]:
Amazon_Sale["ship-postal-code"] = Amazon_Sale["ship-postal-code"].astype("Int64").astype("string")

In [75]:
Amazon_Sale["ship-postal-code"].dtype

In [76]:
missing_amount = Amazon_Sale[Amazon_Sale["Amount"].isnull()]

In [77]:
missing_amount.shape

(7795, 21)

In [78]:
Amazon_Sale[Amazon_Sale["Qty"] == 0]["Status"].value_counts()

Status
Cancelled                       12701
Shipped                            93
Shipped - Delivered to Buyer        8
Shipped - Returned to Seller        3
Pending                             2
Name: count, dtype: int64

In [79]:
Amazon_Sale["Qty_Zero_Flag"] = Amazon_Sale["Qty"] == 0

In [80]:
Amazon_Sale["Qty_Zero_Flag"].value_counts()

Qty_Zero_Flag
False    116168
True      12807
Name: count, dtype: int64

In [81]:
Amazon_Sale[Amazon_Sale["Qty"] < 0].shape

(0, 22)

In [82]:
Amazon_Sale[Amazon_Sale["Qty"] < 0]["Status"].value_counts()

Series([], Name: count, dtype: int64)

In [83]:
Amazon_Sale.loc[Amazon_Sale["Qty"] < 0, ["Order ID", "Qty", "Status"]]

Empty DataFrame
Columns: [Order ID, Qty, Status]
Index: []

In [84]:
Amazon_Sale["Qty"].min()

np.int64(0)

In [85]:
Amazon_Sale[Amazon_Sale["Amount"] == 0]["Status"].value_counts()

Status
Shipped                          1518
Shipped - Delivered to Buyer      716
Shipped - Returned to Seller       51
Shipped - Picked Up                28
Pending                            17
Pending - Waiting for Pick Up       9
Shipped - Lost in Transit           2
Shipped - Returning to Seller       2
Name: count, dtype: int64

In [86]:
Amazon_Sale["Category"].value_counts()

Category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [87]:
Amazon_Sale["Category"] = Amazon_Sale["Category"].str.title()

In [88]:
Amazon_Sale["Category"].value_counts()

Category
Set              50284
Kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [89]:
Amazon_Sale["Size"].value_counts()

Size
M       22711
L       22132
XL      20876
XXL     18096
S       17090
3XL     14816
XS      11161
6XL       738
5XL       550
4XL       427
Free      378
Name: count, dtype: int64

In [90]:
Amazon_Sale["Status"].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [91]:
Amazon_Sale.columns = Amazon_Sale.columns.str.strip()

In [92]:
Amazon_Sale.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'Qty_Zero_Flag'],
      dtype='str')

In [94]:
Amazon_Sale.columns = Amazon_Sale.columns.str.strip()

In [95]:
Amazon_Sale.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'Qty_Zero_Flag'],
      dtype='str')

# Data Validation

In [96]:
Amazon_Sale["Sales Channel"].value_counts()

Sales Channel
Amazon.in     128851
Non-Amazon       124
Name: count, dtype: int64

In [97]:
Amazon_Sale["ship-service-level"].value_counts()

ship-service-level
Expedited    88615
Standard     40360
Name: count, dtype: int64

In [98]:
Amazon_Sale["SKU"].isnull().sum()

np.int64(0)

In [99]:
Amazon_Sale["ASIN"].isnull().sum()

np.int64(0)

In [100]:
Amazon_Sale["Order ID"].isnull().sum()

np.int64(0)

In [101]:
Amazon_Sale["Order ID"].duplicated().sum()

np.int64(8597)

In [102]:
Amazon_Sale["Style"].isnull().sum()

np.int64(0)

In [103]:
Amazon_Sale["B2B"].value_counts()

B2B
False    128104
True        871
Name: count, dtype: int64

In [104]:
Amazon_Sale["Date"].min(), Amazon_Sale["Date"].max()

(Timestamp('2022-03-31 00:00:00'), Timestamp('2022-06-29 00:00:00'))

In [105]:
Amazon_Sale[["Qty", "Amount"]].describe()

                 Qty         Amount
count  128975.000000  121180.000000
mean        0.904431     648.561465
std         0.313354     281.211687
min         0.000000       0.000000
25%         1.000000     449.000000
50%         1.000000     605.000000
75%         1.000000     788.000000
max        15.000000    5584.000000

In [106]:
Amazon_Sale.isnull().sum()

Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       0
Style                    0
SKU                      0
Category                 0
Size                     0
ASIN                     0
Courier Status        6872
Qty                      0
currency              7795
Amount                7795
ship-city                0
ship-state               0
ship-postal-code        33
ship-country             0
promotion-ids            0
B2B                      0
Qty_Zero_Flag            0
dtype: int64

In [107]:
Amazon_Sale[
    (Amazon_Sale["Status"] == "Cancelled") &
    (Amazon_Sale["Qty"] > 0)
].shape

(5631, 22)

In [108]:
Amazon_Sale[
    Amazon_Sale["Status"] == "Cancelled"
]["Amount"].isnull().value_counts()

Amount
False    10766
True      7566
Name: count, dtype: int64

In [109]:
Amazon_Sale.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'Qty_Zero_Flag'],
      dtype='str')

In [110]:
Amazon_Sale.drop(columns=["Qty_Zero_Flag"], inplace=True)

In [111]:
Amazon_Sale.duplicated().sum()

np.int64(6)

In [112]:
Amazon_Sale.shape

(128975, 21)

In [113]:
Amazon_Sale[Amazon_Sale.duplicated(keep=False)]

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B
30660,406-0372545-6086735,2022-04-12,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,L,...,Cancelled,0,NaN,NaN,Siliguri,WEST BENGAL,734008,IN,No Promotion,False
30661,406-0372545-6086735,2022-04-12,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,L,...,Cancelled,0,NaN,NaN,Siliguri,WEST BENGAL,734008,IN,No Promotion,False
41291,408-0373839-4433120,2022-04-05,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,Kurta,M,...,Cancelled,0,NaN,NaN,BENGALURU,KARNATAKA,560072,IN,No Promotion,False
41292,408-0373839-4433120,2022-04-05,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,Kurta,M,...,Cancelled,0,NaN,NaN,BENGALURU,KARNATAKA,560072,IN,No Promotion,False
79844,171-9628368-5329958,2022-05-07,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,Kurta,L,...,Cancelled,0,NaN,NaN,ERNAKULAM,KERALA,682017,IN,No Promotion,False
79845,171-9628368-5329958,2022-05-07,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,Kurta,L,...,Cancelled,0,NaN,NaN,ERNAKULAM,KERALA,682017,IN,No Promotion,False
85790,171-3249942-2207542,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,XL,...,Shipped,1,INR,939.0,PUNE,MAHARASHTRA,411057,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
85791,171-3249942-2207542,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,XL,...,Shipped,1,INR,939.0,PUNE,MAHARASHTRA,411057,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
86418,405-8669298-3850736,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,Kurta,3XL,...,Shipped,1,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
86419,405-8669298-3850736,2022-05-03,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,Kurta,3XL,...,Shipped,1,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
98954,407-4853873-4978725,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,M,...,Shipped,1,INR,1163.0,Zirakpur,Punjab,140603,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False
98955,407-4853873-4978725,2022-06-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,M,...,Shipped,1,INR,1163.0,Zirakpur,Punjab,140603,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False

In [114]:
Amazon_Sale.drop_duplicates(inplace=True)

In [115]:
Amazon_Sale.duplicated().sum()

np.int64(0)

In [116]:
Amazon_Sale.shape

(128969, 21)

In [117]:
Amazon_Sale.info()

<class 'pandas.DataFrame'>
Index: 128969 entries, 0 to 128974
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128969 non-null  str
 1   Date                128969 non-null  datetime64[us]
 2   Status              128969 non-null  str
 3   Fulfilment          128969 non-null  str
 4   Sales Channel       128969 non-null  str
 5   ship-service-level  128969 non-null  str
 6   Style               128969 non-null  str
 7   SKU                 128969 non-null  str
 8   Category            128969 non-null  str
 9   Size                128969 non-null  str
 10  ASIN                128969 non-null  str
 11  Courier Status      122097 non-null  str
 12  Qty                 128969 non-null  int64
 13  currency            121177 non-null  str
 14  Amount              121177 non-null  float64
 15  ship-city           128969 non-null  str
 16  ship-state          128969 non-null  str
 17  ship-postal-code    128936 non-null  string
 18  ship-country        128969 non-null  str
 19  promotion-ids       128969 non-null  str
 20  B2B                 128969 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(1), int64(1), str(16), string(1)
memory usage: 20.8 MB

In [118]:
Amazon_Sale.reset_index(drop=True, inplace=True)

In [119]:
Amazon_Sale.index

RangeIndex(start=0, stop=128969, step=1)

# Export Cleaned Dataset

In [120]:
Amazon_Sale.to_csv(
    "E:/SQL Project Content/archive (3)/Amazon_Sale_Cleaned.csv",
    index=False
)

In [121]:
import os

os.path.exists(
    "E:/SQL Project Content/archive (3)/Amazon_Sale_Cleaned.csv"
)

True